[package]
name = "hahafunnyman/watchdog"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["wally.toml", "lib", "lib/**/*.luau", "default.project.json"]

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
